#!/usr/bin/env python3
"""
kimodo_replay.py — Replay a Kimodo G1 qpos CSV on the physical robot via LLSdk.

Loads a MuJoCo qpos CSV generated by Kimodo's G1Skeleton34 and replays it
frame-by-frame through LLSdk (rt/lowcmd).  Before any command is sent, the
full joint-target table and safety analysis are displayed, and confirmation
is required.

Safety analysis cross-checks every frame against two constraints from ll_sdk:
  1. Ramp speed  — ll_sdk._ramp_publish defaults to 0.35 rad/s at 50 Hz.
                   If a frame delta would require more ramp time than the
                   frame interval allows, the motion will run slower than
                   generated (RAMP>FRAME).  We send with ramp_speed=0 to
                   honour the frame rate, so large deltas arrive instantly —
                   flagged as INSTANT UNSAFE when |Δq|/Δt > 1.5 rad/s.
  2. Joint limits — from ll_sdk._LEG_LIMITS, arm_fk.JOINT_LIMITS, and
                    low_level_commands.py waist limits.

Usage
-----
    python kimodo_replay.py motion.csv [options]

Options
-------
    --fps FPS       Playback frame rate (default 30)
    --root-dof N    Columns to skip at the start of each CSV row for the
                    root pose.  7 = free joint (3 pos + 4 quat), the MuJoCo
                    default for a humanoid; 0 = joint angles only (default 7)
    --iface IFACE   Network interface (default eth0)
    --domain ID     DDS domain ID — 0 = real robot, 1 = sim (default 0)
    --dry-run       Analyse every frame without connecting to the robot
    --no-color      Disable ANSI colour output

Confirmation prompt (per-frame unless errors are present, which always stop)
----------------------------------------------------------------------------
    y / Enter   Send this frame
    s           Skip this frame (do not update prev_targets)
    a           Send all remaining frames without per-frame confirmation
    q           Quit
"""
from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

# ── Kimodo G1Skeleton34 index → robot joint index mapping ─────────────────────
# Derived from kimodo/skeleton/definitions.py G1Skeleton34.bone_order_names_with_parents
# Skipped: 0 (pelvis root), 7 (left_toe_base), 14 (right_toe_base),
#          25 (left_hand_roll endpoint), 33 (right_hand_roll endpoint)
KIMODO_TO_ROBOT: Dict[int, int] = {
    # left leg
    1: 0,  2: 1,  3: 2,  4: 3,  5: 4,  6: 5,
    # right leg
    8: 6,  9: 7,  10: 8, 11: 9, 12: 10, 13: 11,
    # waist
    15: 12, 16: 13, 17: 14,
    # left arm
    18: 15, 19: 16, 20: 17, 21: 18, 22: 19, 23: 20, 24: 21,
    # right arm
    26: 22, 27: 23, 28: 24, 29: 25, 30: 26, 31: 27, 32: 28,
}

# Human-readable names indexed by Kimodo skeleton position
_KIMODO_NAMES: List[str] = [
    "pelvis",               # 0  root
    "left_hip_pitch",       # 1  → robot 0
    "left_hip_roll",        # 2  → robot 1
    "left_hip_yaw",         # 3  → robot 2
    "left_knee",            # 4  → robot 3
    "left_ankle_pitch",     # 5  → robot 4
    "left_ankle_roll",      # 6  → robot 5
    "left_toe_base",        # 7  endpoint
    "right_hip_pitch",      # 8  → robot 6
    "right_hip_roll",       # 9  → robot 7
    "right_hip_yaw",        # 10 → robot 8
    "right_knee",           # 11 → robot 9
    "right_ankle_pitch",    # 12 → robot 10
    "right_ankle_roll",     # 13 → robot 11
    "right_toe_base",       # 14 endpoint
    "waist_yaw",            # 15 → robot 12
    "waist_roll",           # 16 → robot 13
    "waist_pitch",          # 17 → robot 14
    "left_shoulder_pitch",  # 18 → robot 15
    "left_shoulder_roll",   # 19 → robot 16
    "left_shoulder_yaw",    # 20 → robot 17
    "left_elbow",           # 21 → robot 18
    "left_wrist_roll",      # 22 → robot 19
    "left_wrist_pitch",     # 23 → robot 20
    "left_wrist_yaw",       # 24 → robot 21
    "left_hand_roll",       # 25 endpoint
    "right_shoulder_pitch", # 26 → robot 22
    "right_shoulder_roll",  # 27 → robot 23
    "right_shoulder_yaw",   # 28 → robot 24
    "right_elbow",          # 29 → robot 25
    "right_wrist_roll",     # 30 → robot 26
    "right_wrist_pitch",    # 31 → robot 27
    "right_wrist_yaw",      # 32 → robot 28
    "right_hand_roll",      # 33 endpoint
]

# Reverse map: robot joint → Kimodo index (for name lookup)
_ROBOT_TO_KIMODO: Dict[int, int] = {v: k for k, v in KIMODO_TO_ROBOT.items()}

# ── Joint limits [rad] indexed by robot joint 0-28 ────────────────────────────
# Sources:
#   joints 0-11  — ll_sdk.py _LEG_LIMITS (URDF)
#   joints 12-14 — modules/scripts/low_level_commands.py waist entries
#   joints 15-28 — hand_pose_navigation/arm_fk.py JOINT_LIMITS (URDF)
_JOINT_LIMITS: List[Tuple[float, float]] = [
    # left leg (0-5): hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll
    (-2.5307,  2.8798),
    (-0.5236,  2.9671),
    (-2.7576,  2.7576),
    (-0.087267, 2.8798),
    (-0.87267,  0.5236),
    (-0.2618,   0.2618),
    # right leg (6-11)
    (-2.5307,  2.8798),
    (-2.9671,  0.5236),
    (-2.7576,  2.7576),
    (-0.087267, 2.8798),
    (-0.87267,  0.5236),
    (-0.2618,   0.2618),
    # waist (12-14): yaw, roll, pitch
    (-2.618,  2.618),
    (-0.52,   0.52),
    (-0.52,   0.52),
    # left arm (15-21): shoulder_p/r/y, elbow, wrist_r/p/y
    (-3.0890,  2.6700),
    (-1.5708,  2.2000),
    (-2.1817,  2.1817),
    (-1.0472,  2.0944),
    (-1.9722,  1.9722),
    (-1.6580,  1.6580),
    (-1.6580,  1.6580),
    # right arm (22-28): shoulder_p/r/y, elbow, wrist_r/p/y
    (-2.6700,  3.0890),
    (-2.2000,  1.5708),
    (-2.1817,  2.1817),
    (-1.0472,  2.0944),
    (-1.9722,  1.9722),
    (-1.6580,  1.6580),
    (-1.6580,  1.6580),
]

# ── ll_sdk ramp safety constants ──────────────────────────────────────────────
# From ll_sdk.py: ik_move_EE defaults ramp_speed_rad_s=0.35, ramp_rate_hz=50
# Per-step increment = 0.35/50 = 0.007 rad.
# We replay with ramp_speed=0 (instant) to honour frame timing, so we flag
# joints whose implied velocity exceeds a safe threshold instead.
_RAMP_SPEED_RAD_S = 0.35      # ll_sdk default ramp speed
_RAMP_RATE_HZ     = 50.0      # ll_sdk default ramp publish rate
_RAMP_STEP_RAD    = _RAMP_SPEED_RAD_S / _RAMP_RATE_HZ   # 0.007 rad/step

# Velocity threshold above which an instant send is considered mechanically risky.
# Set to 4× the ramp speed — generous but non-trivial.
_INSTANT_UNSAFE_VEL = _RAMP_SPEED_RAD_S * 4.0   # 1.4 rad/s

# ── ANSI helpers ──────────────────────────────────────────────────────────────
_R  = "\033[91m"   # red
_Y  = "\033[93m"   # yellow
_G  = "\033[92m"   # green
_C  = "\033[96m"   # cyan
_B  = "\033[1m"    # bold
_X  = "\033[0m"    # reset


def _c(text: str, code: str, use_color: bool) -> str:
    return f"{code}{text}{_X}" if use_color else text


# ── CSV loading ───────────────────────────────────────────────────────────────

def load_qpos_csv(path: str, root_dof: int) -> np.ndarray:
    """Load qpos CSV and return (n_frames, 34) array of Kimodo joint angles.

    root_dof columns are stripped from the left of each row.
    The G1Skeleton34 has exactly 34 joints; extra trailing columns are ignored.
    """
    with open(path, newline="") as f:
        first = f.readline().strip()

    # Detect header: if the first field is not numeric, skip the row
    try:
        float(first.split(",")[0].replace("-", "").replace(".", "").replace("e", "e"))
        skip = 0
    except ValueError:
        skip = 1

    data = np.loadtxt(path, delimiter=",", skiprows=skip)
    if data.ndim == 1:
        data = data[np.newaxis, :]

    joint_data = data[:, root_dof:]
    expected = 34
    if joint_data.shape[1] < expected:
        raise ValueError(
            f"Expected ≥{expected} joint columns after skipping root_dof={root_dof}, "
            f"got {joint_data.shape[1]}.\n"
            f"  Try --root-dof 0 if the CSV contains only joint angles."
        )
    return joint_data[:, :expected]


# ── Frame processing ──────────────────────────────────────────────────────────

def frame_to_targets(row: np.ndarray) -> Dict[int, float]:
    return {robot_j: float(row[kimodo_i]) for kimodo_i, robot_j in KIMODO_TO_ROBOT.items()}


def analyse_frame(
    targets: Dict[int, float],
    prev_targets: Optional[Dict[int, float]],
    frame_interval_s: float,
    frame_idx: int,
    n_frames: int,
    use_color: bool,
) -> Tuple[List[str], bool, bool]:
    """Build the per-frame table.

    Returns (lines, has_warnings, has_errors).
    has_errors  → joint limit violated or velocity critically high
    has_warnings → ramp would exceed frame interval (motion distortion risk)
    """
    lines: List[str] = []
    has_warnings = False
    has_errors   = False

    col_w = 92
    sep   = "─" * col_w
    hdr   = (
        f"{'Rbt':>3}  {'Joint name':<22}  "
        f"{'Target':>9}  {'Δq':>9}  "
        f"{'Vel rad/s':>10}  {'Ramp ms':>8}  {'Frame ms':>8}  Status"
    )

    lines.append(_c(sep, _C, use_color))
    lines.append(_c(hdr, _B, use_color))
    lines.append(_c(sep, _C, use_color))

    for robot_j in range(29):
        if robot_j not in targets:
            continue

        target = targets[robot_j]
        lo, hi = _JOINT_LIMITS[robot_j]
        name   = _KIMODO_NAMES[_ROBOT_TO_KIMODO[robot_j]]

        status_parts: List[str] = []
        row_color = _G

        delta_str = "      N/A"
        vel_str   = "       N/A"
        ramp_str  = "     N/A"

        if prev_targets is not None and robot_j in prev_targets:
            delta       = target - prev_targets[robot_j]
            vel         = abs(delta) / frame_interval_s          # rad/s implied
            ramp_time_s = abs(delta) / _RAMP_SPEED_RAD_S        # time at ll_sdk ramp speed
            ramp_ms     = ramp_time_s * 1000.0
            frame_ms    = frame_interval_s * 1000.0

            delta_str = f"{delta:+.5f}"
            vel_str   = f"{vel:10.3f}"
            ramp_str  = f"{ramp_ms:8.1f}"

            if ramp_time_s > frame_interval_s:
                # ll_sdk ramp would take longer than one frame: motion distortion
                status_parts.append("RAMP>FRAME")
                has_warnings = True
                if row_color == _G:
                    row_color = _Y

            if vel > _INSTANT_UNSAFE_VEL:
                # Sending instantly at this velocity is mechanically risky
                status_parts.append(f"INSTANT UNSAFE (>{_INSTANT_UNSAFE_VEL:.1f} rad/s)")
                has_errors = True
                row_color  = _R

        frame_ms_str = f"{frame_interval_s * 1000.0:8.1f}"

        if target < lo or target > hi:
            status_parts.append(f"LIMIT [{lo:.3f}, {hi:.3f}]")
            has_errors = True
            row_color  = _R

        status = ", ".join(status_parts) if status_parts else "OK"
        row = (
            f"  {robot_j:>3}  {name:<22}  "
            f"{target:>9.5f}  {delta_str:>9}  "
            f"{vel_str:>10}  {ramp_str:>8}  {frame_ms_str:>8}  {status}"
        )
        lines.append(_c(row, row_color, use_color))

    lines.append(_c(sep, _C, use_color))
    return lines, has_warnings, has_errors


def _frame_summary(
    targets: Dict[int, float],
    prev_targets: Optional[Dict[int, float]],
    frame_interval_s: float,
    use_color: bool,
) -> str:
    """One-line summary: max Δq, implied ramp time vs frame interval."""
    if prev_targets is None:
        return "  (first frame — no delta available)"

    deltas = {j: abs(targets[j] - prev_targets.get(j, targets[j])) for j in targets}
    max_j  = max(deltas, key=deltas.__getitem__)
    max_dq = deltas[max_j]
    ramp_s = max_dq / _RAMP_SPEED_RAD_S
    fi_s   = frame_interval_s
    ok     = ramp_s <= fi_s

    summary = (
        f"  max |Δq|={max_dq:.5f} rad ({_KIMODO_NAMES[_ROBOT_TO_KIMODO[max_j]]})  "
        f"ramp_time={ramp_s * 1000:.1f} ms  frame_interval={fi_s * 1000:.1f} ms  "
    )
    if ok:
        summary += "→ ramp fits in frame (safe to use ll_sdk ramp)"
    else:
        summary += (
            f"→ ramp overruns by {(ramp_s - fi_s) * 1000:.1f} ms  "
            f"[sending instantly — bypasses ll_sdk._ramp_publish safety]"
        )
    color = _G if ok else _Y
    return _c(summary, color, use_color)


def _prompt(msg: str) -> str:
    try:
        return input(msg).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return "q"


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Replay a Kimodo G1 qpos CSV on the robot via LLSdk.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("csv",                       help="Path to Kimodo qpos CSV file")
    ap.add_argument("--fps",      type=float, default=30.0,  help="Playback FPS (default 30)")
    ap.add_argument("--root-dof", type=int,   default=7,     help="Root DOF columns to skip (default 7)")
    ap.add_argument("--iface",    default="eth0",             help="Network interface (default eth0)")
    ap.add_argument("--domain",   type=int,   default=0,     help="DDS domain ID (default 0)")
    ap.add_argument("--dry-run",  action="store_true",        help="Analyse without connecting")
    ap.add_argument("--no-color", action="store_true",        help="Disable ANSI colour")
    args = ap.parse_args()

    use_color       = not args.no_color and sys.stdout.isatty()
    frame_interval  = 1.0 / args.fps

    # ── Load CSV ──────────────────────────────────────────────────────────────
    print(f"Loading {args.csv} …")
    try:
        qpos = load_qpos_csv(args.csv, args.root_dof)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    n_frames = len(qpos)
    print(
        f"  {n_frames} frames  ·  {args.fps} fps  ·  "
        f"{n_frames / args.fps:.1f} s  ·  "
        f"root_dof={args.root_dof} columns skipped"
    )
    print()

    # ── Safety legend ─────────────────────────────────────────────────────────
    print(_c("Safety thresholds (cross-checked against ll_sdk._ramp_publish):", _B, use_color))
    print(f"  Ramp speed    : {_RAMP_SPEED_RAD_S} rad/s  ({_RAMP_RATE_HZ:.0f} Hz)  → "
          f"{_RAMP_STEP_RAD*1000:.1f} mrad/step")
    print(f"  RAMP>FRAME    : {_c('yellow', _Y, use_color)} — ll_sdk ramp would exceed frame interval; "
          f"sent instantly (bypasses ramp safety)")
    print(f"  INSTANT UNSAFE: {_c('red', _R, use_color)} — implied velocity > {_INSTANT_UNSAFE_VEL:.1f} rad/s "
          f"(4× ramp speed); mechanically risky")
    print(f"  LIMIT         : {_c('red', _R, use_color)} — joint value outside URDF hard limits")
    print()

    # ── Dev-mode warning and initial confirmation ─────────────────────────────
    print(_c("WARNING: LLSdk publishes to rt/lowcmd (all 29 joints, developer mode).", _Y, use_color))
    print(_c("         The MotionSwitcher is released — the robot goes limp briefly.", _Y, use_color))
    print(_c("         Ensure the robot is externally supported before proceeding.", _Y, use_color))
    print()
    if not args.dry_run:
        ans = _prompt("Type 'yes' to connect and begin replay, anything else to abort: ")
        if ans != "yes":
            print("Aborted.")
            sys.exit(0)
        print()

    # ── Connect ───────────────────────────────────────────────────────────────
    sdk = None
    if not args.dry_run:
        _mods = Path(__file__).resolve().parent.parent
        if str(_mods) not in sys.path:
            sys.path.insert(0, str(_mods))
        from ll_sdk import LLSdk  # noqa: PLC0415
        print("Connecting …")
        sdk = LLSdk(iface=args.iface, domain_id=args.domain)
        sdk.enter_dev_mode()
        sdk.get_joint_positions()   # block until lowstate arrives
        print("Connected. Starting replay.\n")

    # ── Replay loop ───────────────────────────────────────────────────────────
    prev_targets: Optional[Dict[int, float]] = None
    send_all = False

    for frame_idx in range(n_frames):
        targets = frame_to_targets(qpos[frame_idx])

        # Build analysis table
        table, has_warnings, has_errors = analyse_frame(
            targets, prev_targets, frame_interval,
            frame_idx, n_frames, use_color,
        )

        # Frame header
        tag = ""
        if has_errors:
            tag = _c("  [ERRORS — confirm carefully]", _R, use_color)
        elif has_warnings:
            tag = _c("  [warnings]", _Y, use_color)

        print(f"\n{_c(f'Frame {frame_idx + 1}/{n_frames}', _B, use_color)}{tag}")
        for line in table:
            print(line)
        print(_frame_summary(targets, prev_targets, frame_interval, use_color))

        # Dry-run: no confirmation needed
        if args.dry_run:
            prev_targets = targets
            continue

        # Errors always pause, even in send_all mode
        if has_errors or not send_all:
            if has_errors:
                prompt_msg = _c(
                    "  Joint limit or velocity violation!  [y]es (unsafe) / [s]kip / [q]uit > ",
                    _R, use_color,
                )
            elif has_warnings:
                prompt_msg = _c(
                    "  Ramp mismatch warning.  [y]es / [s]kip / [a]ll / [q]uit > ",
                    _Y, use_color,
                )
            else:
                prompt_msg = "  [y]es / [s]kip / [a]ll / [q]uit > "

            ans = _prompt(prompt_msg)

            if ans in ("q", "quit"):
                print("Quit.")
                sys.exit(0)
            elif ans in ("s", "skip"):
                # Do not update prev_targets — gap is implicit, next frame delta skipped
                continue
            elif ans in ("a", "all") and not has_errors:
                send_all = True
            elif ans not in ("y", "yes", ""):
                print("  Unrecognised input — skipping frame.")
                continue

        # Send frame
        t0 = time.monotonic()
        sdk.move_ll_joint(targets, ramp_speed_rad_s=0.0)
        elapsed = time.monotonic() - t0
        sleep_s = max(0.0, frame_interval - elapsed)
        if sleep_s > 0:
            time.sleep(sleep_s)

        prev_targets = targets

    print("\nReplay complete.")


if __name__ == "__main__":
    main()
